package cobraApp;


/**
* cobraApp/_ServerCobraImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CobraApp.idl
* 20 ?????? 2017 ?. 16:02:04 GMT+03:00
*/


// Specify interface to our address book
public abstract class _ServerCobraImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements cobraApp.ServerCobra, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ServerCobraImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("viewFile", new java.lang.Integer (0));
    _methods.put ("addFile", new java.lang.Integer (1));
    _methods.put ("deleteData", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cobraApp/ServerCobra/viewFile
       {
         String $result = null;
         $result = this.viewFile ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // cobraApp/ServerCobra/addFile
       {
         String day = in.read_string ();
         this.addFile (day);
         out = $rh.createReply();
         break;
       }

       case 2:  // cobraApp/ServerCobra/deleteData
       {
         String data = in.read_string ();
         this.deleteData (data);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cobraApp/ServerCobra:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ServerCobraImplBase
