package cobraApp;


/**
* cobraApp/ServerCobraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CobraApp.idl
* 20 апреля 2017 г. 16:02:04 GMT+03:00
*/


// Specify interface to our address book
public interface ServerCobraOperations 
{
  String viewFile ();
  void addFile (String day);
  void deleteData (String data);
} // interface ServerCobraOperations
