package cobraApp;


/**
* cobraApp/ServerCobra.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CobraApp.idl
* 20 апреля 2017 г. 16:02:04 GMT+03:00
*/


// Specify interface to our address book
public interface ServerCobra extends ServerCobraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerCobra
