package cobraApp;

/**
* cobraApp/ServerCobraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CobraApp.idl
* 20 апреля 2017 г. 16:02:04 GMT+03:00
*/


// Specify interface to our address book
public final class ServerCobraHolder implements org.omg.CORBA.portable.Streamable
{
  public cobraApp.ServerCobra value = null;

  public ServerCobraHolder ()
  {
  }

  public ServerCobraHolder (cobraApp.ServerCobra initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cobraApp.ServerCobraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cobraApp.ServerCobraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cobraApp.ServerCobraHelper.type ();
  }

}
